### ISSUE TITLE
PROD.In the farm overview page, in the calendar, the last observation date offered is 31 August 2021.

### ISSUE THREAD

**Issue by dafinajeaca** [ogorlab/ogor-frontend#80] opened 2020-05-05 17:44 UTC
![31 august 2021](https://user-images.githubusercontent.com/52447572/81097986-603c4500-8f11-11ea-9bad-4b5881b79b95.png)

**Comment by dafinajeaca** [comment] 2020-05-05 17:46
Account: 
cardana@kcagro.com | libra-staunch-benches

**Comment by alexkiro** [comment] 2020-05-06 04:08
This is the same bug discussed yesterday. The app behaves weirdly when there is no data yet. For now follow the instructions in the notification and come back tomorrow when data is available. 

Duplicate of #69.

**Closed by alexkiro** 2020-05-06 04:08 UTC
Labels: bug, duplicate
